export enum DB_OPERATIONS {
  GET_MINIONS,
  GET_MINIONS_COUNT,
  GET_TAG_CATEGORIES,
  GET_IMPLEMENTATION_CATEGORIES,
  GET_CARDS,
  GET_EPISODES,
  GET_SCENES,
  INITIALIZE_LABELS,
  UPDATE_CARD_FILTER,
  GET_MINION_CARDS,
  GET_CARD_SUBS,
  CREATE_CARD,
  RENAME_CARD,
  DELETE_CARD,
}

export enum DB_TABLES {
  MINIONS = 'minions',
  CARDS = 'cards',
  EPISODES = 'episodes',
  SCENES = 'scenes',
}
